name: cups_ffi
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^1.1.2
  convert: ^3.0.1

dev_dependencies:
  ffigen: ^3.0.0
  lints: ^1.0.1

ffigen:
  name: CupsNative
  description: Bindings to `cups.h`.
  output: 'lib/src/cups_native.dart'
  headers:
    entry-points:
      - 'cups-2.3.3/cups.h'
    include-directives: # include only these header files and necessary structs from other header files
      - '**cups.h'
